### ISSUE TITLE
Exception with Picasso latest (2.71828)

### ISSUE THREAD

**Issue by zuyevpro** [lyft/scissors#100]
java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/***-HdTn0yGaWHs9Wi7co2c6CQ==/split_lib_dependencies_apk.apk)
        at com.lyft.android.scissors.PicassoBitmapLoader.createUsing(PicassoBitmapLoader.java:66)
        at com.lyft.android.scissors.CropViewExtensions.resolveBitmapLoader(CropViewExtensions.java:179)
        at com.lyft.android.scissors.CropViewExtensions$LoadRequest.performLoad(CropViewExtensions.java:91)
        at com.lyft.android.scissors.CropViewExtensions$LoadRequest$1.onGlobalLayout(CropViewExtensions.java:108)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1013)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2692)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7832)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by Mihir3646** [comment]
Did you get any solution? My working code is now not working and getting a crash in live app.

**Comment by zuyevpro** [comment]
I've downgraded Picasso to version 2.5.2

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
