### ISSUE TITLE
Select image not load into crop view 

### ISSUE THREAD

**Issue by Neil1484** [lyft/scissors#104]
**Can't load this image into Crop**
It show some dependence on the Glide image loading library. 

ava.lang.NoSuchMethodError: No direct method <init>(Lcom/bumptech/glide/load/engine/bitmap_recycle/BitmapPool;)V in class Lcom/bumptech/glide/load/resource/bitmap/BitmapTransformation; or its super classes (declaration of 'com.bumptech.glide.load.resource.bitmap.BitmapTransformation' appears in /data/app/packageName-4IuKi66yyKv6uLYyPJH60g==/base.apk)
        at com.lyft.android.scissors.GlideFillViewportTransformation.<init>(GlideFillViewportTransformation.java:29)
        at com.lyft.android.scissors.GlideFillViewportTransformation.createUsing(GlideFillViewportTransformation.java:57)
        at com.lyft.android.scissors.GlideBitmapLoader.createUsing(GlideBitmapLoader.java:59)
        at com.lyft.android.scissors.GlideBitmapLoader.createUsing(GlideBitmapLoader.java:54)
        at com.lyft.android.scissors.CropViewExtensions.resolveBitmapLoader(CropViewExtensions.java:182)
        at com.lyft.android.scissors.CropViewExtensions$LoadRequest.performLoad(CropViewExtensions.java:91)
        at com.lyft.android.scissors.CropViewExtensions$LoadRequest$1.onGlobalLayout(CropViewExtensions.java:108)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:959)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2872)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1874)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8491)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7058)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
