### ISSUE TITLE
Exception with glide

### ISSUE THREAD

**Issue by einschneidend** [lyft/scissors#98]
Can't make it work with any version of glide

`E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/Object;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/packageName/base.apk:classes4.dex)
        at com.lyft.android.scissors.GlideBitmapLoader.load(GlideBitmapLoader.java:45)
        at com.lyft.android.scissors.CropViewExtensions$LoadRequest.performLoad(CropViewExtensions.java:93)
        at com.lyft.android.scissors.CropViewExtensions$LoadRequest$1.onGlobalLayout(CropViewExtensions.java:108)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:982)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2460)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1487)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7501)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
        at android.view.Choreographer.doCallbacks(Choreographer.java:695)
        at android.view.Choreographer.doFrame(Choreographer.java:631)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7229)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
